[package]
name = "replibyte"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dump-parser = { path = "../dump-parser" }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
uriparse = "0.6"
